// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4d0dEJu44hBaC8J8ac9-pP4A5teiX-To',
    appId: '1:1049013354027:web:51116d5977a623263db46e',
    messagingSenderId: '1049013354027',
    projectId: 'flutter-app-4c133',
    authDomain: 'flutter-app-4c133.firebaseapp.com',
    databaseURL: 'https://flutter-app-4c133-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-4c133.firebasestorage.app',
    measurementId: 'G-XNPZEYBVM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDtvk_KHH8zMTI0SycOxpjm4OfXXtBabk',
    appId: '1:1049013354027:android:ff0d81126dfdd9823db46e',
    messagingSenderId: '1049013354027',
    projectId: 'flutter-app-4c133',
    databaseURL: 'https://flutter-app-4c133-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-4c133.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc50vCtiTGFEAjm6L_zPKSxrVgC05qQVU',
    appId: '1:1049013354027:ios:4912872d173110803db46e',
    messagingSenderId: '1049013354027',
    projectId: 'flutter-app-4c133',
    databaseURL: 'https://flutter-app-4c133-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-4c133.firebasestorage.app',
    iosBundleId: 'com.example.tienda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc50vCtiTGFEAjm6L_zPKSxrVgC05qQVU',
    appId: '1:1049013354027:ios:4912872d173110803db46e',
    messagingSenderId: '1049013354027',
    projectId: 'flutter-app-4c133',
    databaseURL: 'https://flutter-app-4c133-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-4c133.firebasestorage.app',
    iosBundleId: 'com.example.tienda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4d0dEJu44hBaC8J8ac9-pP4A5teiX-To',
    appId: '1:1049013354027:web:76bc4be547b4ff7b3db46e',
    messagingSenderId: '1049013354027',
    projectId: 'flutter-app-4c133',
    authDomain: 'flutter-app-4c133.firebaseapp.com',
    databaseURL: 'https://flutter-app-4c133-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-4c133.firebasestorage.app',
    measurementId: 'G-NNS0RVCH5P',
  );
}
